chnage yml file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,15 +30,31 @@ jobs:
       - name: Install Composer Dependencies
         run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
 
-      - name: Deploy to Server via SSH
+      - name: Deploy to Server via SSH Private Key
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
-          password: ${{ secrets.SERVER_PASSWORD }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
           port: ${{ secrets.SERVER_PORT }}
           script: |
             cd /home/velvetapp/admin.velvet-app.com || exit 1
+
+            echo "Current path:"
+            pwd
+
+            echo "Files:"
+            ls -la
+
+            if [ ! -f artisan ]; then
+              echo "artisan file not found"
+              exit 1
+            fi
+
+            if [ ! -f composer.json ]; then
+              echo "composer.json file not found"
+              exit 1
+            fi
 
             git pull origin main
 
